/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pahilopaila.view;

import java.awt.Color;
import java.awt.Graphics; // Import for Graphics
import java.awt.Image;    // Import for Image
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import javax.swing.JPanel;      // Ensure JPanel is imported
import javax.swing.ImageIcon;   // Ensure ImageIcon is imported
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

/**
 *
 * @author Acer
 */
public class LoginPageview extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public LoginPageview() {
        initComponents();
        setupPlaceholderLogic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Component declarations (no changes here, NetBeans generates these)
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        forgotPasswordLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel(); // This is your logo, keep it
        passwordField = new javax.swing.JPasswordField();
        newToPahiloPailaLabel = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        // Initialize jPanel1 as a custom JPanel that paints the background image
        // This must come before other components are added to it.
        jPanel1 = new javax.swing.JPanel() {
            private Image backgroundImage;
            { // Initializer block to load the image once when jPanel1 is created
                try {
                    // Load the image resource
                    backgroundImage = new ImageIcon(getClass().getResource("/Image/Adobe Express - file.jpg")).getImage();
                } catch (Exception e) {
                    System.err.println("Error loading background image for jPanel1: " + e.getMessage());
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g); // Call super.paintComponent for default JPanel painting
                if (backgroundImage != null) {
                    // Draw the image scaled to the panel's current size
                    g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        // The JFrame's content pane still uses AbsoluteLayout to place jPanel1
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // Set the layout for jPanel1 itself, as all other components will be added to it
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // Add jPanel1 (your background panel) to the JFrame's content pane FIRST
        // It covers the entire frame
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 450));

        // NOW, add ALL other UI elements to jPanel1, NOT getContentPane()
        // The AbsoluteConstraints remain the same as they are relative to jPanel1's top-left (0,0)

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel1.setText("Welcome to PahiloPaila");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nepal's gateways to job. Step in. Stand out.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        emailField.setForeground(new java.awt.Color(153, 153, 153));
        emailField.setText("E-mail");
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 220, -1));

        loginButton.setBackground(new java.awt.Color(51, 51, 255));
        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 100, 30));

        forgotPasswordLabel.setBackground(new java.awt.Color(0, 51, 255));
        forgotPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        forgotPasswordLabel.setText("Forgot password?");
        jPanel1.add(forgotPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 130, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pahilopaila_logo.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 50));

        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 220, -1));

        newToPahiloPailaLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        newToPahiloPailaLabel.setText("New to PahiloPaila? ");
        jPanel1.add(newToPahiloPailaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 150, 20));

        Email.setText("Email:");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        // Removed the previous jLabel13 that was acting as a background,
        // as jPanel1 now handles the background image.
        // jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Adobe Express - file.jpg"))); // NOI18N
        // getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPageview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPageview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPageview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPageview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPageview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    // Removed jLabel13 as jPanel1 now handles the background
    private javax.swing.JPanel jPanel1; // Ensure this is declared as JPanel
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel newToPahiloPailaLabel;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables

    // --- Public Getters for Controller to use ---
    public String getEnteredEmail() {
        return emailField.getText();
    }

    public char[] getEnteredPassword() {
        return passwordField.getPassword();
    }

    public JButton getLoginButton() {
        return loginButton;
    }

    public JLabel getNewToPahiloPailaLabel() {
        return newToPahiloPailaLabel;
    }

    public JLabel getForgotPasswordLabel() {
        return forgotPasswordLabel;
    }

    // --- Method to set up placeholder behavior ---
    private void setupPlaceholderLogic() {
        // Placeholder for emailField
        emailField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (emailField.getText().equals("E-mail")) {
                    emailField.setText("");
                    emailField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (emailField.getText().isEmpty()) {
                    emailField.setText("E-mail");
                    emailField.setForeground(new Color(153, 153, 153));
                }
            }
        });
    }
}