/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pahilopaila.view;

import java.awt.Color;
import java.awt.Graphics; // Import for Graphics
import java.awt.Image;    // Import for Image
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import javax.swing.JPanel;      // Ensure JPanel is imported
import javax.swing.ImageIcon;   // Ensure ImageIcon is imported
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

/**
 *
 * @author Acer
 */
public class LoginPageview extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public LoginPageview() {
        initComponents();
        setupPlaceholderLogic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        forgotPasswordLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        newToPahiloPailaLabel = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        forJobSeekers = new javax.swing.JLabel();
        forEmployeers1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel1.setText("Welcome to PahiloPaila");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel4.setText("Nepal's gateways to job. Step in. Stand out.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        emailField.setForeground(new java.awt.Color(153, 153, 153));
        emailField.setText("E-mail");
       
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformed(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 230, 30));

        loginButton.setBackground(new java.awt.Color(0, 0, 102));
        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 100, 30));

        forgotPasswordLabel.setBackground(new java.awt.Color(0, 0, 102));
        forgotPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        forgotPasswordLabel.setForeground(new java.awt.Color(0, 0, 102));
        forgotPasswordLabel.setText("Forgot password?");
        getContentPane().add(forgotPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 130, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pahilopaila_logo.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 50));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 230, 30));

        newToPahiloPailaLabel.setBackground(new java.awt.Color(0, 0, 102));
        newToPahiloPailaLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        newToPahiloPailaLabel.setForeground(new java.awt.Color(0, 0, 102));
        newToPahiloPailaLabel.setText("Create Account");
        getContentPane().add(newToPahiloPailaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 150, 20));

        Email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/profile-user .png"))); // NOI18N
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/locked-computer.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("New to PahiloPaila?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 140, -1));

        forJobSeekers.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        forJobSeekers.setForeground(new java.awt.Color(0, 0, 102));
        forJobSeekers.setText("For Job Seekers");
        forJobSeekers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forJobSeekersMouseClicked(evt);
            }
        });
        getContentPane().add(forJobSeekers, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        forEmployeers1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        forEmployeers1.setForeground(new java.awt.Color(0, 0, 102));
        forEmployeers1.setText("For Employeers");
        forEmployeers1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forEmployeers1MouseClicked(evt);
            }
        });
        getContentPane().add(forEmployeers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Adobe Express - file.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forJobSeekersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forJobSeekersMouseClicked
        // TODO add your handling code here:
        jLabel4.setText("Nepal's gateways to job. Step in. Stand out.");
        emailField.setText("E-mail");
        
    }//GEN-LAST:event_forJobSeekersMouseClicked

    private void forEmployeers1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forEmployeers1MouseClicked
        // TODO add your handling code here:
        jLabel4.setText("Connect with qualified Candidates across Nepal.");
        emailField.setText("Recruiter's mail");
        
    }//GEN-LAST:event_forEmployeers1MouseClicked

    /**
     * @param args the command arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPageview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPageview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPageview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPageview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPageview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel forEmployeers1;
    private javax.swing.JLabel forJobSeekers;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel newToPahiloPailaLabel;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables

    // --- Public Getters for Controller to use ---
    public String getEnteredEmail() {
        return emailField.getText();
    }

    public char[] getEnteredPassword() {
        return passwordField.getPassword();
    }

    public JButton getLoginButton() {
        return loginButton;
    }

    public JLabel getNewToPahiloPailaLabel() {
        return newToPahiloPailaLabel;
    }

    public JLabel getForgotPasswordLabel() {
        return forgotPasswordLabel;
    }

    // --- Method to set up placeholder behavior ---
    private void setupPlaceholderLogic() {
        // Placeholder for emailField
        emailField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (emailField.getText().equals("E-mail"))
                 {
                    emailField.setText("");
                    emailField.setForeground(new Color(153,153,153));
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (emailField.getText().equals("")) {
                    emailField.setText("E-mail");
                    emailField.setForeground(new Color(153, 153, 153));
                }
            }
        });
         passwordField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (new String(passwordField.getPassword()).equals("Password")) {
                    passwordField.setText("");
                    passwordField.setForeground(new Color(153, 153, 153));
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (new String(passwordField.getPassword()).equals("")) {
                    passwordField.setText("Password");
                    passwordField.setForeground(new Color(153, 153, 153));
                }
            }
        });
    }
}