/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pahilopaila.view;

import java.awt.Color;

/**
 *
 * @author Acer
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        companyName = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        forJobsSeekrs = new javax.swing.JLabel();
        forEmployeers = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        confirmPassword = new javax.swing.JPasswordField();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        welcome.setText("Welcome to PahiloPaila");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        message.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        message.setText("Connect with qualified Candidates across Nepal.");
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 310, -1));

        companyName.setForeground(new java.awt.Color(125, 125, 186));
        companyName.setText("Company Name");
        companyName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                companyNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                companyNameFocusLost(evt);
            }
        });
        companyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameActionPerformed(evt);
            }
        });
        getContentPane().add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 220, 30));

        mail.setForeground(new java.awt.Color(125, 125, 186));
        mail.setText("E-mail");
        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFocusLost(evt);
            }
        });
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 220, 30));

        registerButton.setBackground(new java.awt.Color(0, 0, 102));
        registerButton.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 110, 30));

        forJobsSeekrs.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        forJobsSeekrs.setForeground(new java.awt.Color(0, 0, 102));
        forJobsSeekrs.setText("For Job Seekers");
        getContentPane().add(forJobsSeekrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        forEmployeers.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        forEmployeers.setForeground(new java.awt.Color(0, 0, 102));
        forEmployeers.setText("For Employeers");
        getContentPane().add(forEmployeers, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pahilopaila_logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 50));

        password.setText("jPasswordField2");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 220, 30));

        confirmPassword.setText("jPasswordField2");
        getContentPane().add(confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 220, 30));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/profile-user .png"))); // NOI18N
        getContentPane().add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/email_1.png"))); // NOI18N
        getContentPane().add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/locked-computer.png"))); // NOI18N
        getContentPane().add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Adobe Express - file.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 850, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusGained
        // TODO add your handling code here:
        if(mail.getText().equals("E-mail"))
        {
            mail.setText("");
            mail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_mailFocusGained

    private void mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusLost
        // TODO add your handling code here:
        if(mail.getText().equals(""))
        {
            mail.setText("E-mail");
            mail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_mailFocusLost

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void companyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyNameActionPerformed

    private void companyNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameFocusLost
        // TODO add your handling code here:
        if(companyName.getText().equals(""))
        {
            companyName.setText("Name");
            companyName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_companyNameFocusLost

    private void companyNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameFocusGained
        // TODO add your handling code here:

        if(companyName.getText().equals("Name"))
        {
            companyName.setText("");
            companyName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_companyNameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField companyName;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JLabel forEmployeers;
    private javax.swing.JLabel forJobsSeekrs;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField mail;
    private javax.swing.JLabel message;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
