/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pahilopaila.view;

import javax.swing.JButton;

/**
 *
 * @author Acer
 */
public class RegistrationEmployee extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationEmployee
     */
    public RegistrationEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        registerJobSeekerButton = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        registerEmployerButton = new javax.swing.JButton();
        emailField = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerJobSeekerButton.setBackground(new java.awt.Color(0, 0, 102));
        registerJobSeekerButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerJobSeekerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerJobSeekerButton.setText("Register as Job Seeker");
        registerJobSeekerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJobSeekerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerJobSeekerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 180, 40));

        welcome.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        welcome.setText("Welcome to PahiloPaila");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        message.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        message.setText("Nepal's gateways to job. Step in. Stand out.");
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        nameField.setForeground(new java.awt.Color(204, 204, 204));
        nameField.setText("Name/Company Name");
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFieldFocusLost(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 220, 30));

        registerEmployerButton.setBackground(new java.awt.Color(0, 0, 102));
        registerEmployerButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerEmployerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerEmployerButton.setText("Register as Employer");
        registerEmployerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerEmployerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerEmployerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 170, 40));

        emailField.setForeground(new java.awt.Color(204, 204, 204));
        emailField.setText("E-mail");
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 220, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pahilopaila_logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 50));
        getContentPane().add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 220, 30));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 220, 30));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/profile-user .png"))); // NOI18N
        getContentPane().add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/email_1.png"))); // NOI18N
        getContentPane().add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/locked-computer.png"))); // NOI18N
        getContentPane().add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Adobe Express - file.jpg"))); // NOI18N
        background.setText("button");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 450));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        // TODO add your handling code here:

        if(nameField.getText().equals("Name"))
        {
            nameField.setText("");
            nameField.setForeground(new java.awt.Color(153,153,153));
        }
    }//GEN-LAST:event_nameFieldFocusGained

    private void nameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusLost
        // TODO add your handling code here:
        if(nameField.getText().equals(""))
        {
            nameField.setText("Name");
            nameField.setForeground(new java.awt.Color(153,153,153));
        }
    }//GEN-LAST:event_nameFieldFocusLost

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        // TODO add your handling code here:
        if(emailField.getText().equals("E-mail"))
        {
            emailField.setText("");
            emailField.setForeground(new java.awt.Color(153,153,153));
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
        if(emailField.getText().equals(""))
        {
            emailField.setText("E-mail");
            emailField.setForeground(new java.awt.Color(153,153,153));
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void registerJobSeekerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJobSeekerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerJobSeekerButtonActionPerformed

    private void registerEmployerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerEmployerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerEmployerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel message;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerEmployerButton;
    private javax.swing.JButton registerJobSeekerButton;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
  public String getEnteredName() {
        return nameField.getText();
    }

    public String getEnteredEmail() {
        return emailField.getText();
    }

    public char[] getEnteredPassword() { // Return char[] for security with JPasswordField
        return passwordField.getPassword();
    }

    public char[] getEnteredConfirmPassword() { // Return char[] for security with JPasswordField
        return confirmPasswordField.getPassword();
    }


   

    // --- Public Getters for Buttons (to attach listeners) ---
    public JButton getRegisterEmployerButton() {
        return registerEmployerButton;
    }

    public JButton getRegisterJobSeekerButton() {
        return registerJobSeekerButton;
    }

}
